package com.cognizant.testing.entity;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * JPA entity representing a User record persisted in the H2 database.
 * <p>
 * Mapped to the {@code USERS} table defined in {@code schema.sql}.
 */
@Entity
@Table(name = "users")
public class User {

    /**
     * Primary key of the user. Auto-generated when a new user is inserted
     * without an explicit id (e.g. via the POST /users endpoint).
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Display name of the user.
     */
    private String name;

    /**
     * Default no-args constructor required by JPA/Hibernate.
     */
    public User() {
    }

    /**
     * Convenience constructor for creating a fully-populated user.
     *
     * @param id   the user id
     * @param name the user name
     */
    public User(Long id, String name) {
        this.id = id;
        this.name = name;
    }

    /**
     * Convenience constructor for creating a user without an id
     * (used when the id will be generated by the database).
     *
     * @param name the user name
     */
    public User(String name) {
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", name='" + name + '\'' +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        User user = (User) o;
        return java.util.Objects.equals(id, user.id) &&
                java.util.Objects.equals(name, user.name);
    }

    @Override
    public int hashCode() {
        return java.util.Objects.hash(id, name);
    }
}
