-- ============================================================
-- Hands-on 5: Populate country table with the full list of
-- countries exactly as provided in the exercise document.
-- INSERT IGNORE is used so re-running on an already-populated
-- database (e.g. on every app restart with ddl-auto=update)
-- does not throw a duplicate-primary-key error.
-- ============================================================
INSERT IGNORE INTO country (co_code, co_name) VALUES ('AF', 'Afghanistan');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('AL', 'Albania');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('DZ', 'Algeria');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('AS', 'American Samoa');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('AD', 'Andorra');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('AO', 'Angola');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('AI', 'Anguilla');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('AQ', 'Antarctica');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('AG', 'Antigua and Barbuda');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('AR', 'Argentina');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('AM', 'Armenia');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('AW', 'Aruba');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('AU', 'Australia');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('AT', 'Austria');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('AZ', 'Azerbaijan');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('BS', 'Bahamas');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('BH', 'Bahrain');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('BD', 'Bangladesh');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('BB', 'Barbados');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('BY', 'Belarus');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('BE', 'Belgium');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('BZ', 'Belize');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('BJ', 'Benin');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('BM', 'Bermuda');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('BT', 'Bhutan');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('BO', 'Bolivia, Plurinational State of');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('BQ', 'Bonaire, Sint Eustatius and Saba');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('BA', 'Bosnia and Herzegovina');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('BW', 'Botswana');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('BV', 'Bouvet Island');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('BR', 'Brazil');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('IO', 'British Indian Ocean Territory');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('BN', 'Brunei Darussalam');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('BG', 'Bulgaria');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('BF', 'Burkina Faso');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('BI', 'Burundi');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('KH', 'Cambodia');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('CM', 'Cameroon');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('CA', 'Canada');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('CV', 'Cape Verde');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('KY', 'Cayman Islands');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('CF', 'Central African Republic');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('TD', 'Chad');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('CL', 'Chile');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('CN', 'China');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('CX', 'Christmas Island');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('CC', 'Cocos (Keeling) Islands');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('CO', 'Colombia');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('KM', 'Comoros');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('CG', 'Congo');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('CD', 'Congo, the Democratic Republic of the');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('CK', 'Cook Islands');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('CR', 'Costa Rica');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('HR', 'Croatia');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('CU', 'Cuba');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('CW', 'Curaçao');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('CY', 'Cyprus');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('CZ', 'Czech Republic');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('CI', 'Côte d''Ivoire');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('DK', 'Denmark');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('DJ', 'Djibouti');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('DM', 'Dominica');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('DO', 'Dominican Republic');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('EC', 'Ecuador');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('EG', 'Egypt');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('SV', 'El Salvador');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('GQ', 'Equatorial Guinea');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('ER', 'Eritrea');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('EE', 'Estonia');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('ET', 'Ethiopia');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('FK', 'Falkland Islands (Malvinas)');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('FO', 'Faroe Islands');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('FJ', 'Fiji');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('FI', 'Finland');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('FR', 'France');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('GF', 'French Guiana');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('PF', 'French Polynesia');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('TF', 'French Southern Territories');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('GA', 'Gabon');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('GM', 'Gambia');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('GE', 'Georgia');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('DE', 'Germany');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('GH', 'Ghana');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('GI', 'Gibraltar');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('GR', 'Greece');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('GL', 'Greenland');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('GD', 'Grenada');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('GP', 'Guadeloupe');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('GU', 'Guam');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('GT', 'Guatemala');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('GG', 'Guernsey');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('GN', 'Guinea');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('GW', 'Guinea-Bissau');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('GY', 'Guyana');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('HT', 'Haiti');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('HM', 'Heard Island and McDonald Islands');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('VA', 'Holy See (Vatican City State)');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('HN', 'Honduras');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('HK', 'Hong Kong');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('HU', 'Hungary');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('IS', 'Iceland');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('IN', 'India');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('ID', 'Indonesia');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('IR', 'Iran, Islamic Republic of');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('IQ', 'Iraq');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('IE', 'Ireland');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('IM', 'Isle of Man');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('IL', 'Israel');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('IT', 'Italy');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('JM', 'Jamaica');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('JP', 'Japan');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('JE', 'Jersey');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('JO', 'Jordan');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('KZ', 'Kazakhstan');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('KE', 'Kenya');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('KI', 'Kiribati');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('KP', 'Democratic People''s Republic of Korea');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('KR', 'Republic of Korea');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('KW', 'Kuwait');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('KG', 'Kyrgyzstan');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('LA', 'Lao People''s Democratic Republic');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('LV', 'Latvia');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('LB', 'Lebanon');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('LS', 'Lesotho');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('LR', 'Liberia');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('LY', 'Libya');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('LI', 'Liechtenstein');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('LT', 'Lithuania');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('LU', 'Luxembourg');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('MO', 'Macao');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('MK', 'Macedonia, the Former Yugoslav Republic of');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('MG', 'Madagascar');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('MW', 'Malawi');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('MY', 'Malaysia');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('MV', 'Maldives');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('ML', 'Mali');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('MT', 'Malta');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('MH', 'Marshall Islands');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('MQ', 'Martinique');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('MR', 'Mauritania');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('MU', 'Mauritius');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('YT', 'Mayotte');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('MX', 'Mexico');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('FM', 'Micronesia, Federated States of');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('MD', 'Moldova, Republic of');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('MC', 'Monaco');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('MN', 'Mongolia');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('ME', 'Montenegro');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('MS', 'Montserrat');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('MA', 'Morocco');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('MZ', 'Mozambique');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('MM', 'Myanmar');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('NA', 'Namibia');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('NR', 'Nauru');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('NP', 'Nepal');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('NL', 'Netherlands');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('NC', 'New Caledonia');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('NZ', 'New Zealand');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('NI', 'Nicaragua');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('NE', 'Niger');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('NG', 'Nigeria');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('NU', 'Niue');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('NF', 'Norfolk Island');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('MP', 'Northern Mariana Islands');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('NO', 'Norway');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('OM', 'Oman');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('PK', 'Pakistan');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('PW', 'Palau');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('PS', 'Palestine, State of');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('PA', 'Panama');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('PG', 'Papua New Guinea');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('PY', 'Paraguay');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('PE', 'Peru');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('PH', 'Philippines');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('PN', 'Pitcairn');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('PL', 'Poland');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('PT', 'Portugal');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('PR', 'Puerto Rico');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('QA', 'Qatar');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('RO', 'Romania');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('RU', 'Russian Federation');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('RW', 'Rwanda');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('RE', 'Réunion');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('BL', 'Saint Barthélemy');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('SH', 'Saint Helena, Ascension and Tristan da Cunha');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('KN', 'Saint Kitts and Nevis');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('LC', 'Saint Lucia');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('MF', 'Saint Martin (French part)');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('PM', 'Saint Pierre and Miquelon');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('VC', 'Saint Vincent and the Grenadines');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('WS', 'Samoa');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('SM', 'San Marino');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('ST', 'Sao Tome and Principe');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('SA', 'Saudi Arabia');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('SN', 'Senegal');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('RS', 'Serbia');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('SC', 'Seychelles');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('SL', 'Sierra Leone');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('SG', 'Singapore');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('SX', 'Sint Maarten (Dutch part)');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('SK', 'Slovakia');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('SI', 'Slovenia');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('SB', 'Solomon Islands');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('SO', 'Somalia');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('ZA', 'South Africa');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('GS', 'South Georgia and the South Sandwich Islands');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('SS', 'South Sudan');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('ES', 'Spain');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('LK', 'Sri Lanka');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('SD', 'Sudan');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('SR', 'Suriname');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('SJ', 'Svalbard and Jan Mayen');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('SZ', 'Swaziland');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('SE', 'Sweden');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('CH', 'Switzerland');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('SY', 'Syrian Arab Republic');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('TW', 'Taiwan, Province of China');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('TJ', 'Tajikistan');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('TZ', 'Tanzania, United Republic of');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('TH', 'Thailand');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('TL', 'Timor-Leste');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('TG', 'Togo');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('TK', 'Tokelau');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('TO', 'Tonga');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('TT', 'Trinidad and Tobago');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('TN', 'Tunisia');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('TR', 'Turkey');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('TM', 'Turkmenistan');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('TC', 'Turks and Caicos Islands');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('TV', 'Tuvalu');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('UG', 'Uganda');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('UA', 'Ukraine');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('AE', 'United Arab Emirates');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('GB', 'United Kingdom');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('US', 'United States');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('UM', 'United States Minor Outlying Islands');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('UY', 'Uruguay');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('UZ', 'Uzbekistan');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('VU', 'Vanuatu');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('VE', 'Venezuela, Bolivarian Republic of');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('VN', 'Viet Nam');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('VG', 'Virgin Islands, British');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('VI', 'Virgin Islands, U.S.');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('WF', 'Wallis and Futuna');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('EH', 'Western Sahara');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('YE', 'Yemen');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('ZM', 'Zambia');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('ZW', 'Zimbabwe');
INSERT IGNORE INTO country (co_code, co_name) VALUES ('AX', 'Åland Islands');